import type { HeaterOption } from '@/types';

export const DEFAULT_HEATERS: HeaterOption[] = [
  {
    id: 'electric_6kw',
    name: 'Electric 6kW',
    description: 'Compact electric heater for small to medium saunas',
    basePrice: 800,
    stoneCapacityPrice: 5,
    chimneyPrice: 0,
    controlPanelPrices: { basic: 0, digital: 150, wifi: 300 },
    hasChimney: false,
    icon: 'Zap',
  },
  {
    id: 'electric_9kw',
    name: 'Electric 9kW',
    description: 'Powerful electric heater for medium to large saunas',
    basePrice: 1200,
    stoneCapacityPrice: 5,
    chimneyPrice: 0,
    controlPanelPrices: { basic: 0, digital: 150, wifi: 300 },
    hasChimney: false,
    icon: 'Zap',
  },
  {
    id: 'wood_burning',
    name: 'Wood-Burning Stove',
    description: 'Traditional wood-fired sauna experience',
    basePrice: 1500,
    stoneCapacityPrice: 4,
    chimneyPrice: 450,
    controlPanelPrices: { basic: 0, digital: 0, wifi: 0 },
    hasChimney: true,
    icon: 'Flame',
  },
  {
    id: 'infrared',
    name: 'Infrared Panels',
    description: 'Modern infrared heating, energy efficient',
    basePrice: 2000,
    stoneCapacityPrice: 0,
    chimneyPrice: 0,
    controlPanelPrices: { basic: 0, digital: 200, wifi: 400 },
    hasChimney: false,
    icon: 'Sun',
  },
  {
    id: 'hybrid',
    name: 'Hybrid System',
    description: 'Combines electric and infrared for versatile heating',
    basePrice: 2800,
    stoneCapacityPrice: 5,
    chimneyPrice: 0,
    controlPanelPrices: { basic: 0, digital: 200, wifi: 400 },
    hasChimney: false,
    icon: 'Sparkles',
  },
];
